### PR TITLE
Update oauth login copy

### PR DESCRIPTION
**Pull request by fitztrev**
"We play nice" is a little too playful/personal. I looked at and translated the other language files and it's the only one that has that tone.

#### French:

*On s'occupe de tout. Vous n'avez qu'à vous connecter.*
*We take care of everything. You only need to log in.*

#### German:

*Wir machen es Ihnen einfach. Sie brauchen sich nur anzumelden.*
*We'll make it easy for you. All you need to do is register.*

#### Turkish:

*İşinizi kolaylaştırıyoruz. Sadece oturum açmanız gerekiyor.*
*We make your job easier. You just need to sign in.*

#### Chinese:

*您只需要登录*
*You only need to log in*

#### Polish:

*To proste. Wystarczy, że się zalogujesz.*
*It's easy. Just sign in.*

#### Russian:

*Мы обо всем позаботимся. Вам достаточно только войти в систему.*
*We take care of everything. You just need to log in.*

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
Trevor,

first of all, thanks.
We have to discuss this internally, if and how this should be added/implemented.
I don't like your version, because the message conveyed is very different (disregarding the tone).

Our version — we don't do any harm to your account/content
Your version — we do everything for you (which is not true :)

**Comment by fitztrev** [comment]
Ok. I chose that because it was used in a couple of the other translations.

**Comment by fitztrev** [comment]
I just pushed a commit with another option. `lineA` is redundant (the `<h1>` already says "Upload a file from [source]"), so I modified `lineA` and `lineB`.

uploadcare-widget

This is just a proposal. I'm throwing out some ideas for options. You can tweak it as you see fit. I just think "We play nice" has got to go. Thanks

**Comment by jeetiss** [comment]
Hi @dmitry-mukhin
What do you think about new proposal?

**Comment by dmitry-mukhin** [comment]
new definition of "new" :)
this is an ongoing internal conversation.

**Pull request closed without merging**
